name: 'Setup Flutter'
description: 'checkout & setup-java & flutter-action & flutter pub get & flutter pub run build_runner build'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter pub run build_runner build
