name: 'Setup Flutter'
description: 'checkout & setup-java & flutter-action & flutter pub get'

inputs:
  channel:
    description: 'channel of flutter'
    required: false
    default: 'master'
  directory:
    description: 'working directory'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ inputs.channel }}

    - run: flutter pub get
      shell: bash
      working-directory: ${{ inputs.directory }}
      
    - run: flutter config --enable-web --enable-linux-desktop --enable-macos-desktop --enable-windows-desktop --enable-android --enable-ios
      shell: bash
